import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { appConfig } from '../src/config.js';
import { Database } from '../src/database.js';
import { preflightUpload, UploadApprovalService, type UploadPolicy } from '../src/services/upload-approval.js';

const dirs:string[]=[];
afterEach(()=>dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true})));
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'deutschz-upload-'));dirs.push(dir);const source=path.join(dir,'settings.json');fs.writeFileSync(source,'{"Enabled":true}','utf8');const policy:UploadPolicy={enabled:true,requireSecondApprover:true,confirmationCodeRequired:true,approvalTimeoutMinutes:10,confirmationCodeTimeoutMinutes:5,globalLock:true,createRemoteBackup:true,maxFileSizeMb:500,maxFiles:100,cooldownSeconds:0,sourceRoots:[dir],targetRoots:['/gameserver/']};return{dir,source,policy};}
async function service(){const f=fixture();const db=await Database.open(path.join(f.dir,'test.sqlite'));return{...f,db,uploads:new UploadApprovalService(db,f.policy)};}

describe('FTP upload approval',()=>{
  it('validates an allowed JSON file and creates a stable SHA-256 manifest',()=>{const f=fixture();const result=preflightUpload(f.source,'/gameserver/profiles/settings.json',f.policy);expect(result.fileCount).toBe(1);expect(result.sha256).toMatch(/^[a-f0-9]{64}$/);});
  it('blocks target traversal and secrets',()=>{const f=fixture();expect(()=>preflightUpload(f.source,'/gameserver/../outside',f.policy)).toThrow(/Zielpfad/);const secret=path.join(f.dir,'.env');fs.writeFileSync(secret,'TOKEN=x');expect(()=>preflightUpload(secret,'/gameserver/.env',f.policy)).toThrow(/Verbotene Datei/);});
  it('requires BISIGN for a PBO',()=>{const f=fixture();const pbo=path.join(f.dir,'mod.pbo');fs.writeFileSync(pbo,'PBO');expect(()=>preflightUpload(pbo,'/gameserver/@Mod/Addons/mod.pbo',f.policy)).toThrow(/BISIGN fehlt/);});
  it('rejects malformed XML and duplicate types',()=>{const f=fixture();const xml=path.join(f.dir,'types.xml');fs.writeFileSync(xml,'<types><type></types>');expect(()=>preflightUpload(xml,'/gameserver/mpmissions/types.xml',f.policy)).toThrow(/Ungültiges XML/);fs.writeFileSync(xml,'<types><type name="A"/><type name="A"/></types>');expect(()=>preflightUpload(xml,'/gameserver/mpmissions/types.xml',f.policy)).toThrow(/Doppelte XML/);});
  it('enforces four eyes and accepts a second approver with a one-time phrase',async()=>{const x=await service();const request=x.uploads.create({requesterUserId:'requester',guildId:'guild',sourcePath:x.source,targetPath:'/gameserver/profiles/settings.json',uploadType:'settings',serverArea:'profiles'});expect(()=>x.uploads.beginApproval(request.requestId,'requester')).toThrow(/Vier-Augen/);const phrase=x.uploads.beginApproval(request.requestId,'approver');expect(phrase).toMatch(/^UPLOAD REQ-/);x.uploads.confirm(request.requestId,'approver',phrase!);expect(x.uploads.get(request.requestId)?.status).toBe('APPROVED');expect(()=>x.uploads.confirm(request.requestId,'approver',phrase!)).toThrow();x.db.close();});
  it('allows the fixed DeutschZ owner to approve their own request',async()=>{const x=await service();const request=x.uploads.create({requesterUserId:appConfig.OWNER_USER_ID,guildId:'guild',sourcePath:x.source,targetPath:'/gameserver/profiles/settings.json',uploadType:'settings',serverArea:'profiles'});const phrase=x.uploads.beginApproval(request.requestId,appConfig.OWNER_USER_ID)!;x.uploads.confirm(request.requestId,appConfig.OWNER_USER_ID,phrase);expect(x.uploads.get(request.requestId)?.status).toBe('APPROVED');x.db.close();});
  it('blocks approval when the file changed after request creation',async()=>{const x=await service();const request=x.uploads.create({requesterUserId:'a',guildId:'guild',sourcePath:x.source,targetPath:'/gameserver/profiles/settings.json',uploadType:'settings',serverArea:'profiles'});fs.writeFileSync(x.source,'{"Enabled":false}');expect(()=>x.uploads.beginApproval(request.requestId,'b')).toThrow(/geändert/);x.db.close();});
  it('uses a mocked atomic executor and never performs real FTP in tests',async()=>{const x=await service();x.policy.confirmationCodeRequired=false;const uploads=new UploadApprovalService(x.db,x.policy);const request=uploads.create({requesterUserId:'a',guildId:'guild',sourcePath:x.source,targetPath:'/gameserver/profiles/settings.json',uploadType:'settings',serverArea:'profiles'});uploads.beginApproval(request.requestId,'b');const executor={uploadAtomic:vi.fn(async()=>undefined),rollback:vi.fn(async()=>undefined)};await uploads.execute(request.requestId,executor);expect(executor.uploadAtomic).toHaveBeenCalledOnce();expect(uploads.get(request.requestId)?.status).toBe('SUCCESS');x.db.close();});
  it('defaults runtime upload execution to disabled',()=>{expect(appConfig.UPLOAD_ENABLED).toBe(false);});
  it('marks interrupted uploads UNKNOWN on recovery',async()=>{const x=await service();const request=x.uploads.create({requesterUserId:'a',guildId:'guild',sourcePath:x.source,targetPath:'/gameserver/profiles/settings.json',uploadType:'settings',serverArea:'profiles'});x.db.run("UPDATE upload_requests SET status='UPLOADING' WHERE request_id=?",[request.requestId]);expect(x.uploads.recoverInterrupted()).toBe(1);expect(x.uploads.get(request.requestId)?.status).toBe('UNKNOWN');x.db.close();});
});
